spring.application.name=voice-assistant-chatbot
spring.banner.image.location=classpath:/banner.txt
spring.main.web-application-type=none

# --- OLLAMA (LLM y Embeddings 100% Locales) ---
# Conexión a la instancia de Ollama en tu PC
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:1b
spring.ai.ollama.embedding.options.model=nomic-embed-text

# --- WHISPER LOCAL (STT) ---
# Apuntamos el cliente de OpenAI a un servidor local de Whisper (ej. whisper.cpp o LocalAI)
spring.ai.openai.base-url=http://localhost:8080
spring.ai.openai.api-key=local
spring.ai.openai.chat.enabled=false
spring.ai.openai.embedding.enabled=false
spring.ai.openai.audio.transcription.options.model=whisper-1

# --- KOKORO LOCAL (TTS) ---
# Apuntamos el cliente de Speech a un contenedor local de Kokoro API
spring.ai.openai.audio.speech.base-url=http://localhost:8880
spring.ai.openai.audio.speech.options.model=kokoro
# Aquí le indicas el nombre exacto de tu archivo de perfil de voz clonado (sin la extensión .pt)
spring.ai.openai.audio.speech.options.voice=voz_pelayo

chatbot.prompt=classpath:/marvin.paranoid.android.txt
# chatbot.prompt=classpath:/psychoanalyst.txt